### ISSUE TITLE
401 ip不支持看这里

### ISSUE THREAD

**Issue by xiaozhou26** [aurora-develop/aurora#104]
BASE_URL=“https://auroraxf.glitch.me/api” （CN网络无法使用）
BASE_URL="https://api.angelxf.cf/api"      （快速）
环境变量已支持自定义base_url，使用代理的url可以绕过限制
 
由于滥用严重 服务器苦不受堪 故关闭免费网关

**Comment by cshitian** [comment]
可以了。不过好像有点卡，慢

**Comment by xiaozhou26** [comment]
毕竟用这个网关转了一次手

**Comment by xiaozhou26** [comment]
毕竟glitch服务器不行，延迟高

**Comment by LiweiDong** [comment]
有哪个链接可以在部署前测试一下ip支不支持？

**Comment by xiaozhou26** [comment]
> 有哪个链接可以在部署前测试一下ip支不支持？

**Comment by callacat** [comment]
`env.template`没改，人多的话会不会卡爆。与`PROXY_URL`是二选一的吧

**Comment by xiaozhou26** [comment]
> `env.template`没改，人多的话会不会卡爆。与`PROXY_URL`是二选一的吧

不是二选一，都可以，主要是我现在服务器配置不高

**Comment by callacat** [comment]
> > `env.template`没改，人多的话会不会卡爆。与`PROXY_URL`是二选一的吧
> 
> 不是二选一，都可以，主要是我现在服务器配置不高

glitch多建几个整个负载均衡怎么样，或者授权信得过的大佬搭建网关

**Comment by xiaozhou26** [comment]
> 有哪个链接可以在部署前测试一下ip支不支持？

没有链接，我可以搓个程序出来

**Comment by Ryan2009** [comment]
> > 有哪个链接可以在部署前测试一下ip支不支持？
> 
> 没有链接，我可以搓个程序出来

还是不太会用. 执行下面的命令，返回值是0. 
curl --location 'http://你的服务器ip:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "stream": true
   }'
用的是docker部署的ghcr.io/aurora-develop/aurora:latest，

**Comment by otherbanana** [comment]
请问 base url 如何自建啊？

**Comment by lx521603** [comment]
{
  "code": 401,
  "message": "response status code is not 200",
  "param": {},
  "type": "InitTurnStile_request_error"
}

不行，3个都试过了

**Comment by lvguanjun** [comment]
BASE_URL="https://api.angelxf.cf/api" 

感觉这个的流式有点问题，看起来是读取了所有响应一起传输过来的，并且有概率 500 状态码，可能是响应时间过长触发超时导致的（当某些 prompt 例如 `写一篇800字的关于人工智能发展的文章` ）。

**Comment by xiaozhou26** [comment]
> `BASE_URL="https://api.angelxf.cf/api" `
> 
> 感觉这个的流式有点问题，看起来是读取了所有响应一起传输过来的，并且有概率 500 状态码，可能是响应时间过长触发超时导致的（当某些 prompt 例如 `写一篇800字的关于人工智能发展的文章` ）。

被你发现了，这个套了vercel加速，vercel不支持流式的。

**Comment by lvguanjun** [comment]
> > `BASE_URL="https://api.angelxf.cf/api" `
> > 感觉这个的流式有点问题，看起来是读取了所有响应一起传输过来的，并且有概率 500 状态码，可能是响应时间过长触发超时导致的（当某些 prompt 例如 `写一篇800字的关于人工智能发展的文章` ）。
> 
> 被你发现了，这个套了vercel加速，vercel不支持流式的。

原来这就是快速的含义啊 /dog

**Comment by xiaozhou26** [comment]
> > > `BASE_URL="https://api.angelxf.cf/api" `
> > > 感觉这个的流式有点问题，看起来是读取了所有响应一起传输过来的，并且有概率 500 状态码，可能是响应时间过长触发超时导致的（当某些 prompt 例如 `写一篇800字的关于人工智能发展的文章` ）。
> > 
> > 
> > 被你发现了，这个套了vercel加速，vercel不支持流式的。
> 
> 原来这就是快速的含义啊 /dog

用一个新加坡的服务器被人打死了，真的不敢不套cdn了

**Comment by luomo-pro** [comment]
这种很多人访问同一个代理，不会很快达到ip限制吗？
我现在是没设置代理，海外的vps可以使用，但不知道用多少后会达限制。
另外有好的 PROXY_URL 厂家推荐吗，谢谢各位大佬~

**Comment by xiaozhou26** [comment]
> 这种很多人访问同一个代理，不会很快达到ip限制吗？ 我现在是没设置代理，海外的vps可以使用，但不知道用多少后会达限制。 另外有好的 PROXY_URL 厂家推荐吗，谢谢各位大佬~

这几个都加代理池了，能自己访问就别用网关
