### ISSUE TITLE
Error: please put HAR files in harPool directory!

### ISSUE THREAD

**Issue by Vitowong00** [aurora-develop/aurora#107]
使用的render部署，
<img width="923" alt="image" src="https://github.com/aurora-develop/aurora/assets/140407974/1075c482-ba65-43fc-a4bd-98ac202dc517">

**Comment by zzxxsscn** [comment]
现在还是出现这样的问题、无法运行

**Comment by xiaozhou26** [comment]
能用就行，这个是用来gpt4的
