### ISSUE TITLE
please put HAR files in harPool directory 这个怎么弄？

### ISSUE THREAD

**Issue by Jesn** [aurora-develop/aurora#11]
![image](https://github.com/aurora-develop/aurora/assets/5728274/b4084525-0404-414c-97e4-2f5f6b8e47b5)

**Comment by MagicalMadoka** [comment]
忽略就行，用开源项目改的，一些无用的代码暂时还没删

**Comment by Jesn** [comment]
我美国服务器，日本服务器都有盾了，有没有什么好的方式过盾？

**Comment by MagicalMadoka** [comment]
首先你要确认真的出盾，在确认真的情况下可以部署这个试试 https://github.com/cockroachai/ja3-proxy
