### ISSUE TITLE
render部署的容器被删（看本文）

### ISSUE THREAD

**Issue by zengge99** [aurora-develop/aurora#115]
是不是被禁了？

**Comment by buwanyuanshen** [comment]
可能被屏蔽了

**Comment by tongxiaofeng1** [comment]
被屏蔽了

**Comment by WhyMeta** [comment]
This action is not allowed. 💊💊💊💊💊🤓

**Comment by WhyMeta** [comment]
解决方案：
1. fork project
2. 增加两个 classic access token，一个 write package，一个 read package
3. 改 build_docker workflow 的 GHCR_REPO 为你自己的
4. 项目设置的repository secret 添加GHCR_PAT参数，值为 write package 的token
5. run actions（生成路径：GHCR_REPO）
6. render 用你自己的GHCR_REPO（会提示找不到），授权你的 read package token 就行了
7. Done.

**Comment by larchsis** [comment]
> 解决方案：
> 
> 1. fork project
> 2. 增加两个 classic access token，一个 write package，一个 read package
> 3. 改 build_docker workflow 的 GHCR_REPO 为你自己的
> 4. 项目设置的repository secret 添加GHCR_PAT参数，值为 write package 的token
> 5. run actions（生成路径：GHCR_REPO）
> 6. render 用你自己的GHCR_REPO（会提示找不到），授权你的 read package token 就行了
> 7. Done.

多谢老哥指导，晚点去尝试一下。

**Comment by buwanyuanshen** [comment]
确实可行，可以去试试

**Comment by buwanyuanshen** [comment]
攻略已给出，可前往linux.do查看！https://linux.do/t/topic/48352/95

**Comment by larchsis** [comment]
> > 解决方案：
> > 
> > 1. fork project
> > 2. 增加两个 classic access token，一个 write package，一个 read package
> > 3. 改 build_docker workflow 的 GHCR_REPO 为你自己的
> > 4. 项目设置的repository secret 添加GHCR_PAT参数，值为 write package 的token
> > 5. run actions（生成路径：GHCR_REPO）
> > 6. render 用你自己的GHCR_REPO（会提示找不到），授权你的 read package token 就行了
> > 7. Done.
> 
> 多谢老哥指导，晚点去尝试一下。

已部署，看看这次能坚持多久。

**Comment by larchsis** [comment]
嗯，已经重新用上了自己的镜像。WhyMeta的步骤没什么问题。

**Comment by zengge99** [comment]
> 攻略已给出，可前往linux.do查看！https://linux.do/t/topic/48352/95

可用，谢谢

**Comment by zengge99** [comment]
已解决

**Comment by xiaozhang959** [comment]
> 解决方案：
> 
>     1. fork project
> 
>     2. 增加两个 classic access token，一个 write package，一个 read package
> 
>     3. 改 build_docker workflow 的 GHCR_REPO 为你自己的
> 
>     4. 项目设置的repository secret 添加GHCR_PAT参数，值为 write package 的token
> 
>     5. run actions（生成路径：GHCR_REPO）
> 
>     6. render 用你自己的GHCR_REPO（会提示找不到），授权你的 read package token 就行了
> 
>     7. Done.

感谢

**Comment by zengge99** [comment]
> 解决方案：
> 
> 1. fork project
> 2. 增加两个 classic access token，一个 write package，一个 read package
> 3. 改 build_docker workflow 的 GHCR_REPO 为你自己的
> 4. 项目设置的repository secret 添加GHCR_PAT参数，值为 write package 的token
> 5. run actions（生成路径：GHCR_REPO）
> 6. render 用你自己的GHCR_REPO（会提示找不到），授权你的 read package token 就行了
> 7. Done.

感谢

**Comment by CarberryChai** [comment]
> 解决方案：
> 
> 1. fork project
> 2. 增加两个 classic access token，一个 write package，一个 read package
> 3. 改 build_docker workflow 的 GHCR_REPO 为你自己的
> 4. 项目设置的repository secret 添加GHCR_PAT参数，值为 write package 的token
> 5. run actions（生成路径：GHCR_REPO）
> 6. render 用你自己的GHCR_REPO（会提示找不到），授权你的 read package token 就行了
> 7. Done.

这个方法也不行了，又被删了😫

**Comment by WhyMeta** [comment]
> > 解决方案：
> > 
> > 1. fork project
> > 2. 增加两个 classic access token，一个 write package，一个 read package
> > 3. 改 build_docker workflow 的 GHCR_REPO 为你自己的
> > 4. 项目设置的repository secret 添加GHCR_PAT参数，值为 write package 的token
> > 5. run actions（生成路径：GHCR_REPO）
> > 6. render 用你自己的GHCR_REPO（会提示找不到），授权你的 read package token 就行了
> > 7. Done.
> 
> 这个方法也不行了，又被删了😫

---

建议 拉取佬的 docker 镜像，自己打 tag 之后 push 到个人的 docker hub，选 public，render / koyeb 重新 create project，使用自己的 docker 镜像。
1. pull 镜像
➜  ~ docker pull ghcr.io/aurora-develop/aurora:latest
 2. 网页登录 docker  hub 账号
 - https://hub.docker.com/settings/security 设置两个 access token
     - 一个 push 镜像用，权限（Read, Write, Delete）
     - 一个 render 和 koyeb 授权用（一般 public image 不需要的，但是它俩经常抽风），权限（Public Repo Read-only）
3. https://hub.docker.com/repositories 创建repo，选择 Public
4. terminal 登录 docker hub 账号
➜  ~ docker login -u {your account}
Password: {push 镜像的 access token}
5. push 镜像
➜  ~ docker tag [镜像 ID / NAME] [新的标签名称 你的repo / 镜像 Name]:tag
> docker tag ghcr.io/aurora-develop/aurora MyRepo/MyImage:latest
➜  ~ docker push MyRepo/MyImage:latest
6. render / koyeb 享用

**Comment by xiaozhang959** [comment]
> > 解决方案：
> > 
> > 1. fork project
> > 2. 增加两个 classic access token，一个 write package，一个 read package
> > 3. 改 build_docker workflow 的 GHCR_REPO 为你自己的
> > 4. 项目设置的repository secret 添加GHCR_PAT参数，值为 write package 的token
> > 5. run actions（生成路径：GHCR_REPO）
> > 6. render 用你自己的GHCR_REPO（会提示找不到），授权你的 read package token 就行了
> > 7. Done.
> 
> 这个方法也不行了，又被删了😫

并没有，我的还在

**Comment by CarberryChai** [comment]
> > > 解决方案：
> > > 
> > > 1. fork project
> > > 2. 增加两个 classic access token，一个 write package，一个 read package
> > > 3. 改 build_docker workflow 的 GHCR_REPO 为你自己的
> > > 4. 项目设置的repository secret 添加GHCR_PAT参数，值为 write package 的token
> > > 5. run actions（生成路径：GHCR_REPO）
> > > 6. render 用你自己的GHCR_REPO（会提示找不到），授权你的 read package token 就行了
> > > 7. Done.
> > 
> > 
> > 这个方法也不行了，又被删了😫
> 
> 建议 拉取佬的 docker 镜像，自己打 tag 之后 push 到个人的 docker hub，选 public，render / koyeb 重新 create project，使用自己的 docker 镜像。
> 
> 1. pull 镜像
>    ➜  ~ docker pull ghcr.io/aurora-develop/aurora:latest
> 2. 网页登录 docker  hub 账号
> 
> * https://hub.docker.com/settings/security 设置两个 access token
>   
>   * 一个 push 镜像用，权限（Read, Write, Delete）
>   * 一个 render 和 koyeb 授权用（一般 public image 不需要的，但是它俩经常抽风），权限（Public Repo Read-only）
> 
> 3. https://hub.docker.com/repositories 创建repo，选择 Public
> 4. terminal 登录 docker hub 账号
>    ➜  ~ docker login -u {your account}
>    Password: {push 镜像的 access token}
> 5. push 镜像
>    ➜  ~ docker tag [镜像 ID / NAME] [新的标签名称 你的repo / 镜像 Name]:tag
> 
> > docker tag ghcr.io/aurora-develop/aurora MyRepo/MyImage:latest
> > ➜  ~ docker push MyRepo/MyImage:latest
> 
> 6. render / koyeb 享用

多谢！！
我想强调一下，这里面有一个坑。
用mac M芯片的注意了！！
第一步，`docker pull`下来的是linux/arm架构的，render不支持，只支持linux/amd64
最好还是`git clone`，自己本地重新build
```shell
docker buildx build --platform=linux/amd64 .
```

**Comment by zengge99** [comment]
> > > 解决方案：
> > > 
> > > 1. fork project
> > > 2. 增加两个 classic access token，一个 write package，一个 read package
> > > 3. 改 build_docker workflow 的 GHCR_REPO 为你自己的
> > > 4. 项目设置的repository secret 添加GHCR_PAT参数，值为 write package 的token
> > > 5. run actions（生成路径：GHCR_REPO）
> > > 6. render 用你自己的GHCR_REPO（会提示找不到），授权你的 read package token 就行了
> > > 7. Done.
> > 
> > 
> > 这个方法也不行了，又被删了😫
> 
> 建议 拉取佬的 docker 镜像，自己打 tag 之后 push 到个人的 docker hub，选 public，render / koyeb 重新 create project，使用自己的 docker 镜像。
> 
> 1. pull 镜像
>    ➜  ~ docker pull ghcr.io/aurora-develop/aurora:latest
> 2. 网页登录 docker  hub 账号
> 
> * https://hub.docker.com/settings/security 设置两个 access token
>   
>   * 一个 push 镜像用，权限（Read, Write, Delete）
>   * 一个 render 和 koyeb 授权用（一般 public image 不需要的，但是它俩经常抽风），权限（Public Repo Read-only）
> 
> 3. https://hub.docker.com/repositories 创建repo，选择 Public
> 4. terminal 登录 docker hub 账号
>    ➜  ~ docker login -u {your account}
>    Password: {push 镜像的 access token}
> 5. push 镜像
>    ➜  ~ docker tag [镜像 ID / NAME] [新的标签名称 你的repo / 镜像 Name]:tag
> 
> > docker tag ghcr.io/aurora-develop/aurora MyRepo/MyImage:latest
> > ➜  ~ docker push MyRepo/MyImage:latest
> 
> 6. render / koyeb 享用

自己build的也不行了

**Comment by zengge99** [comment]
> > > > 解决方案：
> > > > 
> > > > 1. fork project
> > > > 2. 增加两个 classic access token，一个 write package，一个 read package
> > > > 3. 改 build_docker workflow 的 GHCR_REPO 为你自己的
> > > > 4. 项目设置的repository secret 添加GHCR_PAT参数，值为 write package 的token
> > > > 5. run actions（生成路径：GHCR_REPO）
> > > > 6. render 用你自己的GHCR_REPO（会提示找不到），授权你的 read package token 就行了
> > > > 7. Done.
> > > 
> > > 
> > > 这个方法也不行了，又被删了😫
> > 
> > 
> > 建议 拉取佬的 docker 镜像，自己打 tag 之后 push 到个人的 docker hub，选 public，render / koyeb 重新 create project，使用自己的 docker 镜像。
> > 
> > 1. pull 镜像
> >    ➜  ~ docker pull ghcr.io/aurora-develop/aurora:latest
> > 2. 网页登录 docker  hub 账号
> > 
> > 
> > * https://hub.docker.com/settings/security 设置两个 access token
> >   
> >   * 一个 push 镜像用，权限（Read, Write, Delete）
> >   * 一个 render 和 koyeb 授权用（一般 public image 不需要的，但是它俩经常抽风），权限（Public Repo Read-only）
> > 
> > 
> > 3. https://hub.docker.com/repositories 创建repo，选择 Public
> > 4. terminal 登录 docker hub 账号
> >    ➜  ~ docker login -u {your account}
> >    Password: {push 镜像的 access token}
> > 5. push 镜像
> >    ➜  ~ docker tag [镜像 ID / NAME] [新的标签名称 你的repo / 镜像 Name]:tag
> > 
> > > docker tag ghcr.io/aurora-develop/aurora MyRepo/MyImage:latest
> > > ➜  ~ docker push MyRepo/MyImage:latest
> > 
> > 
> > 
> > 6. render / koyeb 享用
> 
> 自己build的也不行了

fork出来，修改dockerfile的镜像底包（具体哪个就自己发挥，一窝蜂容易挂），然后结合上述各个大神的方法。实测可行

**Comment by HumanMus1c** [comment]
晚了，账号已经被suspended.😭

**Comment by jingdizhilh** [comment]
render 死磕到底，弃了吧

**Comment by sylvan99** [comment]
docker改名字也不行了

**Comment by tianlichunhong** [comment]
教程是不是被删除了？看不了了。能否放到其他地方吗？感谢！

**Comment by wisonli** [comment]
按照教程去部署render，成功是成功了。但是今天早上就被删除了。哎！

**Comment by zengge99** [comment]
> 按照教程去部署render，成功是成功了。但是今天早上就被删除了。哎！

没用的，各种方法都试过了，教程没写的方法也试过了，顶多撑1天。

**Comment by hhhaiai** [comment]
我靠，开源都不让玩，那开个毛

**Comment by hhhaiai** [comment]
建议 拉取佬的 docker 镜像，自己打 tag 之后 push 到个人的 docker hub，选 public，render / koyeb 重新 create project，使用自己的 docker 镜像。

    pull 镜像
    ➜ ~ docker pull ghcr.io/aurora-develop/aurora:latest
    网页登录 docker hub 账号

    https://hub.docker.com/settings/security 设置两个 access token
        一个 push 镜像用，权限（Read, Write, Delete）
        一个 render 和 koyeb 授权用（一般 public image 不需要的，但是它俩经常抽风），权限（Public Repo Read-only）

    https://hub.docker.com/repositories 创建repo，选择 Public
    terminal 登录 docker hub 账号
    ➜ ~ docker login -u {your account}
    Password: {push 镜像的 access token}
    push 镜像
    ➜ ~ docker tag [镜像 ID / NAME] [新的标签名称 你的repo / 镜像 Name]:tag

    docker tag ghcr.io/aurora-develop/aurora MyRepo/MyImage:latest
    ➜ ~ docker push MyRepo/MyImage:latest

    render / koyeb 享用
