### ISSUE TITLE
Error: please put HAR files in harPool directory!

### ISSUE THREAD

**Issue by kufei326** [aurora-develop/aurora#121]
编译错误Error: please put HAR files in harPool directory!arm64的机器

**Comment by kufei326** [comment]
![IMG_4781](https://github.com/aurora-develop/aurora/assets/73808426/6af5cbf1-c490-4d3f-a663-372a024e6551)

**Comment by xiaozhou26** [comment]
不用管这个，这个是gpt4用的，close issue一大堆这个问题

**Comment by xiaozhou26** [comment]
> 我的ip用free3.5用不了，用你的项目就行。我以为是因为你的项目有HAR文件？难道不是吗😳 我看你fork的原项目写了3.5和4都要有这个文件

不是，和Har没有关系，本项目har是用来过gpt4的，接口都是我抓的官方新接口，应该是全网第一个，其他都是跟着我换或者没有换的，当然有限制。

**Comment by flyapple2016** [comment]
> > 我的ip用free3.5用不了，用你的项目就行。我以为是因为你的项目有HAR文件？难道不是吗😳 我看你fork的原项目写了3.5和4都要有这个文件
> 
> 不是，和Har没有关系，本项目har是用来过gpt4的，接口都是我抓的官方新接口，应该是全网第一个，其他都是跟着我换或者没有换的，当然有限制。

感谢解答
