### ISSUE TITLE
Render button is not working!

### ISSUE THREAD

**Issue by amrpyt** [aurora-develop/aurora#122]
i got this error:

![Screenshot 2024-04-06 050802](https://github.com/aurora-develop/aurora/assets/77219001/ab1bcadf-e28d-4b86-be0c-df6dbdcba78c)

**Comment by xiaozhou26** [comment]
render flagged our project and I'm not sure what the reason is

**Comment by amrpyt** [comment]
Can I install it locally on my **Windows machine?**

**Comment by xiaozhou26** [comment]
> Can I install it locally on my **Windows machine?**

sure

**Comment by amrpyt** [comment]
> > Can I install it locally on my **Windows machine?**
> 
> 
> 
> sure

How?

**Comment by xiaozhou26** [comment]
> > > Can I install it locally on my **Windows machine?**
> > 
> > 
> > sure
> 
> How?

https://github.com/aurora-develop/aurora/blob/main/README_EN.md
Compilation Deployment

**Comment by vkingw** [comment]
> i got this error:
> 
> ![Screenshot 2024-04-06 050802](https://private-user-images.githubusercontent.com/77219001/320173811-ab1bcadf-e28d-4b86-be0c-df6dbdcba78c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzk1NTAsIm5iZiI6MTcxMjM3OTI1MCwicGF0aCI6Ii83NzIxOTAwMS8zMjAxNzM4MTEtYWIxYmNhZGYtZTI4ZC00Yjg2LWJlMGMtZGY2ZGJkY2JhNzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA0NTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZjQ4M2RlYmM0NGZlYWNhNGEyNDhlYmM2NDVmNDFjNjE3ZDIxMDRmZTZkZDllZGM3OGY4Mjc3ZjNiNDRjZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j0I5UGM48X9hURIlZ7by45fymnR0Ec2ERlR9Wq5t14s)

If releasing the image to Docker Hub is now available. I have released one on Docker Hub, feel free to use it.   It works on me.

vincentking/aurora:latest

**Comment by luoyujian** [comment]
![image](https://github.com/aurora-develop/aurora/assets/28535222/dd7b3a55-ae39-4ab5-816d-91545bf074fe)
是不是被render屏蔽了😂昨天还可以

**Comment by xiaozhou26** [comment]
> ![image](https://private-user-images.githubusercontent.com/28535222/320185762-dd7b3a55-ae39-4ab5-816d-91545bf074fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzOTEwMjgsIm5iZiI6MTcxMjM5MDcyOCwicGF0aCI6Ii8yODUzNTIyMi8zMjAxODU3NjItZGQ3YjNhNTUtYWUzOS00YWI1LTgxNmQtOTE1NDViZjA3NGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA4MDUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMjE2YjgwNDQzZWY1ZmU3MzhlZjEwYmRhNDQ2NWY3MWZkY2U4NDI1YTkxZTczYTk3ZmEyNDFiODhmNjdhNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JmnsB-4jb_pBsluiaeqJ6J-NbuB90HA8xP_ePkmbnq8) 是不是被render屏蔽了😂昨天还可以

被屏蔽了
