### ISSUE TITLE
curl没有响应

### ISSUE THREAD

**Issue by alexluoli** [aurora-develop/aurora#125]
![image](https://github.com/aurora-develop/aurora/assets/14903888/4ef9e9c8-f8c4-4a25-81ee-1d7e3ae99ab5)

**Comment by xiaozhou26** [comment]
新镜像吗

**Comment by alexluoli** [comment]
是的

**Comment by xiaozhou26** [comment]
重新拉

**Comment by alexluoli** [comment]
重新拉也是一样

**Comment by xiaozhou26** [comment]
能免登吗

**Comment by alexluoli** [comment]
不懂“能免登”什么意思

**Comment by xiaozhou26** [comment]
就是官网能不用登录使用gpt3.5对话吗

**Comment by xiaozhou26** [comment]
#137

**Comment by alexluoli** [comment]
我这vps是美国的，跟我在国内fq使用gpt无关系吧？

**Comment by xiaozhou26** [comment]
> 我这vps是美国的，跟我在国内fq使用gpt无关系吧？

有的服务器ip不支持免登，或者风控强使用不了，更新这一班镜像

**Comment by alexluoli** [comment]
![image](https://github.com/aurora-develop/aurora/assets/14903888/eb448c71-deb0-43fb-91dd-8a4e4fd384ff)
确实，要“验证真人”

**Comment by alexluoli** [comment]
这样的话，能否跳过？

**Comment by xiaozhou26** [comment]
> 这样的话，能否跳过？

ip太黑了

**Comment by xiaozhou26** [comment]
加baseurl变量就行

**Comment by alexluoli** [comment]
加baseurl变量就行，请问什么意思？
