### ISSUE TITLE
请问长时间无响应, 最后 503 了

### ISSUE THREAD

**Issue by gebederry** [aurora-develop/aurora#126]
![tjuFo.png](https://i.imgs.ovh/2024/04/05/tjuFo.png)

**Comment by xiaozhou26** [comment]
能免登吗

**Comment by gebederry** [comment]
> 能免登吗

也不行，web UI 中发送对话，回复内容为空，立时返回 404

**Comment by xiaozhou26** [comment]
奇怪了，节点能提共一下吗？你是哪里ip

**Comment by gebederry** [comment]
> 奇怪了，节点能提共一下吗？你是哪里ip

vir 的 🇯🇵 小🐥，我把小鸡发你，没找到你的电邮

**Comment by xiaozhou26** [comment]
xiaoxiaofeihh@gmail.com

**Comment by gebederry** [comment]
> [xiaoxiaofeihh@gmail.com](mailto:xiaoxiaofeihh@gmail.com)

请查收 168***@qq

**Comment by xiaozhou26** [comment]
> > [xiaoxiaofeihh@gmail.com](mailto:xiaoxiaofeihh@gmail.com)
> 
> 请查收 168***@qq

ok

**Comment by xiaozhou26** [comment]
ip太黑了

加baseurl
