### ISSUE TITLE
直接使用web端时出现：无权使用此模型，请选择其他GPT模型！

### ISSUE THREAD

**Issue by bccahy** [aurora-develop/aurora#129]
可以使用api，但是网页对话不了？

https://aurora-la
使用镜像：https://github.com/aurora-develop/aurora/issues/122#issuecomment-2040966753

http://172.233.137.
使用最新镜像
ghcr.io/aurora-develop/aurora         latest    c4ea1f094830   About an hour ago   23.9MB

用F12看了一下，好像是请求url的问题？
http://172.233.137.23
![image](https://github.com/aurora-develop/aurora/assets/88807223/d32b2f10-98e7-4364-ab16-d8ac58750b88)
![image](https://github.com/aurora-develop/aurora/assets/88807223/69f94db4-9e58-47a6-b5fc-1444796fb435)

左下角设置改成
https://aurora-latest-kv8h.onrender.com/能用

**Comment by xiaozhou26** [comment]
改了就能用了
没有默认
