### ISSUE TITLE
Improving Version Control with .gitattributes File

### ISSUE THREAD

**Issue by Cunninger** [aurora-develop/aurora#136]
- [x] 我已确认目前没有类似 issue
- [x] 我已确认目前没有类似 issue
- [x]  我已确认我已升级到最新版本
- [x]  我已完整查看过项目 README，已确定现有版本无法满足需求
- [x]  我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

## `.gitattributes` 文件可以用于定义项目中文件的属性，以优化项目的版本控制。

1. 定义行尾风格：，`.gitattributes` 文件可以用于定义行尾风格。你可以设置所有的 `.go` 和 [`.html`](command:_github.copilot.openSymbolInFile?%5B%22aurora%2Fweb%2Findex.html%22%2C%22.html%22%5D "aurora/web/index.html") 文件在提交时自动转换为 LF 行尾，而在检出时转换为 CRLF 行尾。

    ```gitattributes
    *.go text eol=lf
    *.html text eol=lf
    ```

3. 定义文件的合并策略：`.gitattributes` 文件可以用于定义特定文件的合并策略。可以设置所有的 [`.json`](command:_github.copilot.openSymbolInFile?%5B%22aurora%2Fweb%2Findex.html%22%2C%22.json%22%5D "aurora/web/index.html") 文件使用 `merge=ours` 策略，这意味着在合并冲突时，总是选择当前分支的版本。

    ```gitattributes
    *.json merge=ours
    ```

**Comment by xiaozhou26** [comment]
#134

**Comment by xiaozhou26** [comment]
感谢您的支持
