### ISSUE TITLE
koyeb部署无法正常使用

### ISSUE THREAD

**Issue by fengguowudi** [aurora-develop/aurora#139]
https://planned-lorianna-yunfeiyang.koyeb.app/
使用返回500错误码。尝试更换过环境变量中的baseurl 

控制台log有以下报错出现
2024/04/06 08:30:35 [Recovery] 2024/04/06 - 08:30:35 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/layers/heroku_go/shim/go1.21.5/go/src/runtime/panic.go:261 (0x44def7)
/layers/heroku_go/shim/go1.21.5/go/src/runtime/signal_unix.go:861 (0x44dec5)
/workspace/internal/chatgpt/request.go:225 (0x8cbe5d)
	InitTurnStile: defer response.Body.Close()
/workspace/handlers.go:173 (0x8e4524)
	(*Handler).nightmare: turnStile, status, err := chatgpt.InitTurnStile(client, secret, proxyUrl, 5)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8e6baf)
[GIN] 2024/04/06 - 08:30:35 | 500 |  9.144953309s | 193.122.113.204 | POST     "/v1/chat/completions"
/workspace/middleware.go:33 (0x8e6af4)
	Authorization: c.Next()
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8e6955)
/workspace/middleware.go:14 (0x8e6943)
	cors: c.Next()
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8b4599)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x8b4587)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8b373d)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x8b3700)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8b27fa)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x8b248d)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x8b213c)
/layers/heroku_go/shim/go1.21.5/go/src/net/http/server.go:2938 (0x6ac48d)
/layers/heroku_go/shim/go1.21.5/go/src/net/http/server.go:2009 (0x6a9133)
/layers/heroku_go/shim/go1.21.5/go/src/runtime/asm_amd64.s:1650 (0x46a3e0)
2024/04/06 08:30:44 [Recovery] 2024/04/06 - 08:30:44 panic recovered:
[GIN] 2024/04/06 - 08:30:44 | 500 | 14.685266049s | 193.122.113.204 | POST     "/v1/chat/completions"
runtime error: invalid memory address or nil pointer dereference
/layers/heroku_go/shim/go1.21.5/go/src/runtime/panic.go:261 (0x44def7)
/layers/heroku_go/shim/go1.21.5/go/src/runtime/signal_unix.go:861 (0x44dec5)
/workspace/internal/chatgpt/request.go:225 (0x8cbe5d)
	InitTurnStile: defer response.Body.Close()
/workspace/handlers.go:173 (0x8e4524)
	(*Handler).nightmare: turnStile, status, err := chatgpt.InitTurnStile(client, secret, proxyUrl, 5)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8e6baf)
/workspace/middleware.go:33 (0x8e6af4)
	Authorization: c.Next()
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8e6955)
/workspace/middleware.go:14 (0x8e6943)
	cors: c.Next()
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8b4599)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x8b4587)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8b373d)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x8b3700)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8b27fa)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x8b248d)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x8b213c)
/layers/heroku_go/shim/go1.21.5/go/src/net/http/server.go:2938 (0x6ac48d)
/layers/heroku_go/shim/go1.21.5/go/src/net/http/server.go:2009 (0x6a9133)
/layers/heroku_go/shim/go1.21.5/go/src/runtime/asm_amd64.s:1650 (0x46a3e0)
[GIN] 2024/04/06 - 08:30:53 | 500 | 20.395820899s | 193.122.113.204 | POST     "/v1/chat/completions"
2024/04/06 08:30:53 [Recovery] 2024/04/06 - 08:30:53 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/layers/heroku_go/shim/go1.21.5/go/src/runtime/panic.go:261 (0x44def7)
/layers/heroku_go/shim/go1.21.5/go/src/runtime/signal_unix.go:861 (0x44dec5)
/workspace/internal/chatgpt/request.go:225 (0x8cbe5d)
	InitTurnStile: defer response.Body.Close()
/workspace/handlers.go:173 (0x8e4524)
	(*Handler).nightmare: turnStile, status, err := chatgpt.InitTurnStile(client, secret, proxyUrl, 5)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8e6baf)
/workspace/middleware.go:33 (0x8e6af4)
	Authorization: c.Next()
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8e6955)
/workspace/middleware.go:14 (0x8e6943)
	cors: c.Next()
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8b4599)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x8b4587)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8b373d)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x8b3700)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8b27fa)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x8b248d)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x8b213c)
/layers/heroku_go/shim/go1.21.5/go/src/net/http/server.go:2938 (0x6ac48d)
/layers/heroku_go/shim/go1.21.5/go/src/net/http/server.go:2009 (0x6a9133)
/layers/heroku_go/shim/go1.21.5/go/src/runtime/asm_amd64.s:1650 (0x46a3e0)
2024/04/06 08:32:04 [Recovery] 2024/04/06 - 08:32:04 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/layers/heroku_go/shim/go1.21.5/go/src/runtime/panic.go:261 (0x44def7)
/layers/heroku_go/shim/go1.21.5/go/src/runtime/signal_unix.go:861 (0x44dec5)
/workspace/internal/chatgpt/request.go:225 (0x8cbe5d)
	InitTurnStile: defer response.Body.Close()
/workspace/handlers.go:173 (0x8e4524)
	(*Handler).nightmare: turnStile, status, err := chatgpt.InitTurnStile(client, secret, proxyUrl, 5)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8e6baf)
/workspace/middleware.go:33 (0x8e6af4)
	Authorization: c.Next()
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8e6955)
/workspace/middleware.go:14 (0x8e6943)
	cors: c.Next()
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8b4599)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x8b4587)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8b373d)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x8b3700)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8b27fa)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x8b248d)
/layers/heroku_go/shim/go-path/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x8b213c)
/layers/heroku_go/shim/go1.21.5/go/src/net/http/server.go:2938 (0x6ac48d)
/layers/heroku_go/shim/go1.21.5/go/src/net/http/server.go:2009 (0x6a9133)
/layers/heroku_go/shim/go1.21.5/go/src/runtime/asm_amd64.s:1650 (0x46a3e0)
[GIN] 2024/04/06 - 08:32:04 | 500 |  8.808112068s | 193.122.113.204 | POST     "/v1/chat/completions"

**Comment by xiaozhou26** [comment]
这是basuirl替换出错了，环境变量写错了

**Comment by xiaozhou26** [comment]
欧洲不支持，可以加baseurl环境变量突破

**Comment by xiaozhou26** [comment]
地区选美国重新搭建
