### ISSUE TITLE
如何流式打印返回的内容

### ISSUE THREAD

**Issue by tianlichunhong** [aurora-develop/aurora#14]
我看是支持stream=ture的。请问如何流式打印返回的内容？请大侠指导。
我使用的python代码是这样的：
import requests
import json
url = "http://127.0.0.1:8080/v1/chat/completions"
headers = {"Content-Type": "application/json"}
data = {
    "model": "gpt-3.5-turbo",
    "messages": [{
        "role": "user",
        "content": "Hi"
    }],
    "stream":True
}
response = requests.post(url, headers=headers, data=json.dumps(data))

**Comment by xiaozhou26** [comment]
支持流式的

**Comment by xiaozhou26** [comment]
import requests
import json

url = 'http://127.0.0.1:8080/v1/chat/completions'
headers = {'Content-Type': 'application/json'}
data = {
    "model": "gpt-3.5-turbo",
    "messages": [{"role": "user", "content": "Say this is a test!"}],
    "stream": True
}

response = requests.post(url, headers=headers, data=json.dumps(data))

print('HTTP Status Code:', response.status_code)
print('Response Body:', response.text)

if response.status_code == 200:
    try:
        print('JSON Response:', response.json())
    except json.JSONDecodeError:
        print('Could not decode the response as JSON')
else:
    print('Received an error:', response.status_code)

**Comment by tianlichunhong** [comment]
这个不是stream的打印。是一次行将返回内容的打印（就是结果返回完成，才一次性打印出来。我研究了一下，给大家一个完整的参考吧！
`import requests
import json

url = "http://127.0.0.1:8080/v1/chat/completions"
headers = {'Accept': 'text/event-stream'}
data = {
    "model": "gpt-3.5-turbo",
    "messages": [{
        "role": "user",
        "content": "Hello!"
    }],
    "stream":True
}

proxies = {
    "http": "http://127.0.0.1:8090",
    "https": "http://127.0.0.1:8090"
}

response = requests.post(url, stream=True,headers=headers, data=json.dumps(data), proxies=proxies)
for line in response.iter_lines(decode_unicode=True):
    if line:
        if line.startswith("data:"):
            event_data = line[5:].strip()
            if event_data =='[DONE]':
                break
            try:
                event_json = json.loads(event_data)
                if 'content' in event_json['choices'][0]['delta']:
                    print(event_json['choices'][0]['delta']['content'], end="", flush=True)
            except json.JSONDecodeError as e:
                print("Error decoding JSON:", e)
        else:
            print("Invalid SSE format")
response.close()`
