### ISSUE TITLE
render已标记该仓库

### ISSUE THREAD

**Issue by xiaozhou26** [aurora-develop/aurora#146]
render已标记该仓库

**Comment by leadscloud** [comment]
fork后的仓库仍然不行，被封禁了，之前搭建的没任何通知，直接删除

**Comment by xiaozhou26** [comment]
你不改名字肯定一样啊

**Comment by summerKK** [comment]
我咋说我的用不了了😂

**Comment by chunzha1** [comment]
> 你不改名字肯定一样啊
不太懂render，需要fork+改名字吗？

**Comment by huawuhen** [comment]
dockerfile都有自己构建一个不就行了,或者你可以用我的huawuhen/freewebgpt
