### ISSUE TITLE
部署koyeb后访问出错

### ISSUE THREAD

**Issue by alexluoli** [aurora-develop/aurora#149]
![image](https://github.com/aurora-develop/aurora/assets/14903888/c6c16514-6839-4b76-a99f-02b44f1fdeee)

**Comment by alexluoli** [comment]
所以部署koyeb也废了

**Comment by xiaozhou26** [comment]
> 所以部署koyeb也废了

没有啊，别人可以用

**Comment by xiaozhou26** [comment]
项目不知名风控，导致ip过不了
