### ISSUE TITLE
【询问】请问github actions打包的docker镜像是如何关联到仓库的

### ISSUE THREAD

**Issue by RedShameA** [aurora-develop/aurora#157]
![image](https://github.com/aurora-develop/aurora/assets/31084981/3b0de162-d9fe-499c-95e1-27cf6fe4361d)
如图，你的仓库可以关联到你发布的docker镜像

我fork的aurora action[打包的镜像](https://github.com/users/RedShameA/packages/container/package/aurora)无法关联到我fork出来的[仓库](https://github.com/RedShameA/aurora)上
![image](https://github.com/aurora-develop/aurora/assets/31084981/c44ee121-a2e3-4653-8432-ce9153202d89)

**Comment by MagicalMadoka** [comment]
去 package那边关联
