### ISSUE TITLE
可以支持转化为api么？

### ISSUE THREAD

**Issue by justincnn** [aurora-develop/aurora#161]
这样就可以支持一些自己的项目了

**Comment by MagicalMadoka** [comment]
你好支持的，api才是主要的功能，可以参考readme的usage部分

**Comment by justincnn** [comment]
> 你好支持的，api才是主要的功能，可以参考readme的usage部分

这个需要自己有openai账号，才能把token转化为api对么？这个项目可以自己生成api么？
然后用http://你的服务器ip:8080/v1/chat/completions这个接口？

谢谢

~~~yaml
curl --location 'http://你的服务器ip:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "stream": true
   }'
~~~

**Comment by MagicalMadoka** [comment]
不需要账号

**Comment by alegoho** [comment]
你好，你可以用了么？我DOCKER部署好了，但安usage部分搞还是出错


404 page not foundcurl: (6) Could not resolve host: header
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: data
curl: (3) nested brace in URL position 51:

**Comment by justincnn** [comment]
> 不需要账号

谢谢回复，但是在easydict中，如果不填入账号的话，没法使用，具体请看图

![](https://s2.loli.net/2024/04/08/9wDZ3814GfQvePn.png)

**Comment by alegoho** [comment]
> > 不需要账号
> 
> 谢谢回复，但是在easydict中，如果不填入账号的话，没法使用，具体请看图
> 
> ![](https://camo.githubusercontent.com/6f5236de2fb7c67849c0563750b319de255aa31432184fddbfb01ad0e0dcce04/68747470733a2f2f73322e6c6f6c692e6e65742f323032342f30342f30382f3977445a333831344766517665506e2e706e67)

你将你的http://你的服务器ip:8080/v1/chat/completions 填到 完整接口地址 那里，API KEY填什么都可以
