### ISSUE TITLE
请求报错：PROTOCOL_ERROR， type='InitTurnStile_request_error'

### ISSUE THREAD

**Issue by AnonymousmousCoder** [aurora-develop/aurora#163]
ChatCompletion(id=None, choices=None, created=None, model=None, object=None, system_fingerprint=None, usage=None, code=0, message='Post "https://api.angelxf.cf/api/sentinel/chat-requirements": stream error: stream ID 1; PROTOCOL_ERROR', param={'Op': 'Post', 'URL': 'https://api.angelxf.cf/api/sentinel/chat-requirements', 'Err': {'StreamID': 1, 'Code': 1, 'Cause': None}}, type='InitTurnStile_request_error')

**Comment by xiaozhou26** [comment]
那就不填网关了，这是可选项
