### ISSUE TITLE
一键部署不太行奥。。。

### ISSUE THREAD

**Issue by buwanyuanshen** [aurora-develop/aurora#164]
第一个vercel部署，部署成功，绑定了域名，但是没结果返回。
第二个render，按照linux.do攻略可以部署，国内可直接用，不用绑域名。
第三个koyeb，部署成功，国内无法直接使用，绑定域名要绑卡。
第四个railway，部署失败火车出轨了。。。
第五个zeabur,部署后，报错服务暂停：Service is suspended
Service is suspended and it will be inaccessible until you reactivate it. Suspended services won't be charged for usage.

**Comment by xiaozhou26** [comment]
1.是因为只能非流式客户端使用
4.有点问题，目前没有成功的
5.你是被举报了，删除了，这个好像要充钱

**Comment by li5bo5** [comment]
没有域名的小白只会一键部署、所以“第二个render”大佬能出个更加详细的教程嘛？ @buwanyuanshen

**Comment by buwanyuanshen** [comment]
> 没有域名的小白只会一键部署、所以“第二个render”大佬能出个更加详细的教程嘛？ @buwanyuanshen

请看这个https://linux.do/t/topic/47725/83

**Comment by li5bo5** [comment]
> > 没有域名的小白只会一键部署、所以“第二个render”大佬能出个更加详细的教程嘛？ @buwanyuanshen
> 
> 请看这个https://linux.do/t/topic/47725/83

好的，非常感谢

**Comment by dongbao66** [comment]
> > > 没有域名的小白只会一键部署、所以“第二个render”大佬能出个更加详细的教程嘛？ @buwanyuanshen
> > 
> > 
> > 请看这个https://linux.do/t/topic/47725/83
> 
> 好的，非常感谢！！ 但是该论坛目前仅限邀请注册。无法查看该贴。。。
邀请链接
https://junlong.plus/ztool/clipboard/zcaha1

**Comment by li5bo5** [comment]
> > > > 没有域名的小白只会一键部署、所以“第二个render”大佬能出个更加详细的教程嘛？ @buwanyuanshen
> > > 
> > > 
> > > 请看这个https://linux.do/t/topic/47725/83
> > 
> > 
> > 好的，非常感谢！！ 但是该论坛目前仅限邀请注册。无法查看该贴。。。
> > 邀请链接
> > https://junlong.plus/ztool/clipboard/zcaha1

万分感谢！！！！！

**Comment by dongbao66** [comment]
> > > > > 没有域名的小白只会一键部署、所以“第二个render”大佬能出个更加详细的教程嘛？ @buwanyuanshen
> > > > 
> > > > 
> > > > 请看这个https://linux.do/t/topic/47725/83
> > > 
> > > 
> > > 好的，非常感谢！！ 但是该论坛目前仅限邀请注册。无法查看该贴。。。
> > > 邀请链接
> > > https://junlong.plus/ztool/clipboard/zcaha1
> 
> 大佬你好，可以给我个linux.do的邀请码吗


邀请链接
https://linux.do/invites/4Nuygn5Tyu

**Comment by DavidZhiXing** [comment]
> 1.是因为只能非流式客户端使用 5.你是被举报了，删除了，这个好像要充钱

原来是这样啊，我说怎么OpenAI Translator没响应...没早看...zeabur的账户看来也废了，免费的VPS也不好茹啊
