### ISSUE TITLE
对话提示"error": true,"message": "Failed to fetch"

### ISSUE THREAD

**Issue by sally624** [aurora-develop/aurora#165]
使用的是ChatGPT-Next-Web最新版V2.11.3，测试API通过github的codespace的docker方式部属，填入的API链接(已将端口设为公开)为https://xxx-8080.app.github.dev/v1/chat/completions ，也试过vercel方式部属，填入的API链接为https://xxx.vercel.app/v1/chat/completions ，但是对话后都提示下面的报错，请问大佬该怎么解决？

```
{
  "error": true,
  "message": "Failed to fetch"
}
```

**Comment by xiaozhou26** [comment]
post吗

**Comment by xiaozhou26** [comment]
不支持在next-web这些默认流式的客户端

**Comment by sylvan99** [comment]
{
  "error": true,
  "message": "empty response"
}

**Comment by sylvan99** [comment]
> > { "error": true, "message": "empty response" }
> 
> 你这个是vercel布署的API？

render部署的 昨天重启render后正常了
