### ISSUE TITLE
无权使用此模型，请选择其他GPT模型！

### ISSUE THREAD

**Issue by DGUTyu** [aurora-develop/aurora#177]
![image](https://github.com/aurora-develop/aurora/assets/46373156/58f7976c-cc39-4e38-9c9a-8dbb9df260e8)
无权使用此模型，请选择其他GPT模型！3.5使用不了

**Comment by firimar** [comment]
默认的请求地址有问题，多了一层web 需要自己填一下

**Comment by xiaozhou26** [comment]
> 默认的请求地址有问题，多了一层web 需要自己填一下

不用改吧

**Comment by xiaozhou26** [comment]
应该是ip问题

**Comment by firimar** [comment]
> 应该是ip问题

<img width="469" alt="image" src="https://github.com/aurora-develop/aurora/assets/20078939/8ad505f5-4f8b-4ebe-8e60-fd0dbf576b2a">

<img width="310" alt="image" src="https://github.com/aurora-develop/aurora/assets/20078939/37ca761f-3569-47f3-8389-f8a30884ca3f">
上面正常 下面默认报错

**Comment by xiaozhou26** [comment]
> > 应该是ip问题
> 
> <img alt="image" width="469" src="https://private-user-images.githubusercontent.com/20078939/320721696-8ad505f5-4f8b-4ebe-8e60-fd0dbf576b2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Mzc0ODAsIm5iZiI6MTcxMjYzNzE4MCwicGF0aCI6Ii8yMDA3ODkzOS8zMjA3MjE2OTYtOGFkNTA1ZjUtNGY4Yi00ZWJlLThlNjAtZmQwZGJmNTc2YjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA0MzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MzZkZTdmNzU5ZTU0YjE1M2IwNzljMTQ0YmNkYTI5YjNlNDA3OTFiNjU5MzQ5YjQyY2NmZTQzZDA4ZmY0NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._L3PXgPSDkopc6lksdbXGEVcJsE2U5Te5xk9kB-s8Pg"> <img alt="image" width="310" src="https://private-user-images.githubusercontent.com/20078939/320721762-37ca761f-3569-47f3-8389-f8a30884ca3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Mzc0ODAsIm5iZiI6MTcxMjYzNzE4MCwicGF0aCI6Ii8yMDA3ODkzOS8zMjA3MjE3NjItMzdjYTc2MWYtMzU2OS00N2YzLTgzODktZjhhMzA4ODRjYTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA0MzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMDgwZTk3NDY5MDUxZmQxNWU5Yjg5MzkwYTQ1NGQ3YjRhZGFjOTZiMGY1YzhiMWRkOTZkMTc5MDJjOTAxMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qP1Tf5aCqbV1mFxJFpFTnqI_qOQXKxjZn1Un-nkYu6M"> 上面正常 下面默认报错

那我不知道别人是直接开箱即用的，你是不是没有拉新版本镜像

**Comment by firimar** [comment]
> > > 应该是ip问题
> > 
> > 
> > <img alt="image" width="469" src="https://private-user-images.githubusercontent.com/20078939/320721696-8ad505f5-4f8b-4ebe-8e60-fd0dbf576b2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Mzc0ODAsIm5iZiI6MTcxMjYzNzE4MCwicGF0aCI6Ii8yMDA3ODkzOS8zMjA3MjE2OTYtOGFkNTA1ZjUtNGY4Yi00ZWJlLThlNjAtZmQwZGJmNTc2YjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA0MzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MzZkZTdmNzU5ZTU0YjE1M2IwNzljMTQ0YmNkYTI5YjNlNDA3OTFiNjU5MzQ5YjQyY2NmZTQzZDA4ZmY0NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._L3PXgPSDkopc6lksdbXGEVcJsE2U5Te5xk9kB-s8Pg"> <img alt="image" width="310" src="https://private-user-images.githubusercontent.com/20078939/320721762-37ca761f-3569-47f3-8389-f8a30884ca3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Mzc0ODAsIm5iZiI6MTcxMjYzNzE4MCwicGF0aCI6Ii8yMDA3ODkzOS8zMjA3MjE3NjItMzdjYTc2MWYtMzU2OS00N2YzLTgzODktZjhhMzA4ODRjYTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA0MzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMDgwZTk3NDY5MDUxZmQxNWU5Yjg5MzkwYTQ1NGQ3YjRhZGFjOTZiMGY1YzhiMWRkOTZkMTc5MDJjOTAxMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qP1Tf5aCqbV1mFxJFpFTnqI_qOQXKxjZn1Un-nkYu6M"> 上面正常 下面默认报错
> 
> 那我不知道别人是直接开箱即用的，你是不是没有拉新版本镜像

确实是这样 ， 更新后好了
