### ISSUE TITLE
couple issues

### ISSUE THREAD

**Issue by amrpyt** [aurora-develop/aurora#178]
1:

[Issue] OpenAI/openai: Unauthorized - failed to get chat requirements

2:

**[Service Issue] Openai**: Internal Server Error (500): 
  "error": {
    "code": "500",
    "details": "",
    "message": "Unknown error",
    "param": null,
    "type": "internal_server_error"
  }

**Comment by coulsontl** [comment]
遇到了同样的问题，回滚到这个版本就正常了 ghcr.io/aurora-develop/aurora:6663325954d47258250eaa9c79089977eb28146e

**Comment by xiaozhou26** [comment]
拉新镜像重试

**Comment by amrpyt** [comment]
> 拉新镜像重试

[Issue] OpenAI/openai: Forbidden - "object": "list", "data": null - is "https://depressed-sharai-amrpyt.koyeb.app/v1/models" accessible by the server?

**Comment by sylvan99** [comment]
{
  "error": "Our systems have detected unusual activity from your device. Please try again later."
}
