### ISSUE TITLE
环境变量PROXY_URL未生效

### ISSUE THREAD

**Issue by RedShameA** [aurora-develop/aurora#181]
## 确定代理地址及端口正确可用
![image](https://github.com/aurora-develop/aurora/assets/31084981/0a59f7f5-5fb6-4a79-b3d7-a18fc0e2e72f)
## 此时代理日志显示了连接
![image](https://github.com/aurora-develop/aurora/assets/31084981/fe48c446-e739-41fd-93c2-489fe110c774)
## docker环境变量已正确配置
![image](https://github.com/aurora-develop/aurora/assets/31084981/c367a34c-547c-48bc-836c-2a44682d3dd6)

**Comment by learnLi** [comment]
请求协议呢？

**Comment by RedShameA** [comment]
> Collaborator
加上协议依然不行
![image](https://github.com/aurora-develop/aurora/assets/31084981/c38406b9-eac1-41e1-9df8-5242c1ec61c1)

**Comment by learnLi** [comment]
你是本地部署吗？如果是本地部署先看看你的代理连接是否可以在本地上访问chatgpt。然后docker容器发出的请求是通过宿主机访问网络的。你可以不用额外填写代理

**Comment by MagicalMadoka** [comment]
hi ，建议你先保证docker的网络和代理的网络在一个网段上面。这不是本项目应该关心的问题

**Comment by xiaozhou26** [comment]
> 你是本地部署吗？如果是本地部署先看看你的代理连接是否可以在本地上访问chatgpt。然后docker容器发出的请求是通过宿主机访问网络的。你可以不用额外填写代理

他填写方式不是错的吗，肯定不行
