### ISSUE TITLE
这个如何解决？

### ISSUE THREAD

**Issue by aston314** [aurora-develop/aurora#184]
2024/04/09 20:48:43 [aurora-main] aurora imports
2024/04/09 20:48:43 [aurora-main] 	aurora/initialize imports
2024/04/09 20:48:43 [aurora-main] 	log/slog: package log/slog is not in GOROOT (/usr/local/go/src/log/slog)
2024/04/09 20:48:43 [aurora-main] aurora imports
2024/04/09 20:48:43 [aurora-main] 	aurora/initialize imports
2024/04/09 20:48:43 [aurora-main] 	aurora/httpclient/bogdanfinn imports
2024/04/09 20:48:43 [aurora-main] 	github.com/bogdanfinn/fhttp imports
2024/04/09 20:48:43 [aurora-main] 	github.com/bogdanfinn/utls imports
2024/04/09 20:48:43 [aurora-main] 	crypto/ecdh: package crypto/ecdh is not in GOROOT (/usr/local/go/src/crypto/ecdh)
2024/04/09 20:48:43 
2024/04/09 20:48:44 [aurora-main] exit status 1

**Comment by learnLi** [comment]
少了2个包
crypto/ecdh: package crypto/ecdh is not in GOROOT (/usr/local/go/src/crypto/ecdh)
log/slog: package log/slog is not in GOROOT (/usr/local/go/src/log/slog)

**Comment by aston314** [comment]
对 如何解决

**Comment by learnLi** [comment]
google
