### ISSUE TITLE
访问密码不正确或为空，请前往登录页输入正确的访问密码，或者在设置页填入你自己的 OpenAI API Key。

### ISSUE THREAD

**Issue by lx521603** [aurora-develop/aurora#186]
访问密码不正确或为空，请前往登录页输入正确的访问密码，或者在设置页填入你自己的 OpenAI API Key。

{
  "code": 401,
  "message": "response status code is not 200",
  "param": {},
  "type": "InitTurnStile_request_error"
}

请问我这个是什么原因？

如果不通过chatgpt-next-web的话

{"message":"Hello, world!"}

每天我都拉去最新镜像了

**Comment by xiaozhou26** [comment]
ip不能用呗，刷爆了，并发太多就黑了
