### ISSUE TITLE
套了cloudflare以后，api key提示访问密码不正确或为空，请前往登录页输入正确的访问密码

### ISSUE THREAD

**Issue by alecctv** [aurora-develop/aurora#196]
套了cloudflare以后，api key提示访问密码不正确或为空，请前往登录页输入正确的访问密码。关掉cf就是好的

{
  "code": 401,
  "message": "failed to get chat requirements",
  "param": {},
  "type": "InitTurnStile_request_error"
}

大佬，这个有解决办法么

**Comment by chris-ss** [comment]
aurora没设置Authorization的情况下,api_key随便填就行
