### ISSUE TITLE
一键部署不成功

### ISSUE THREAD

**Issue by 393695510** [aurora-develop/aurora#198]
打开显示{"message":"Hello, world!"}

**Comment by chris-ss** [comment]
这就代表你部署成功了 
调用api就行了 http://你的服务器ip:8080/v1/chat/completions
web界面在  http://你的服务器ip:8080/web

**Comment by 393695510** [comment]
感谢，我还以为直接打开就是web端

**Comment by 393695510** [comment]
> 这就代表你部署成功了 调用api就行了 [http://你的服务器ip:8080/v1/chat/completions](http://%E4%BD%A0%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8ip:8080/v1/chat/completions) web界面在 [http://你的服务器ip:8080/web](http://%E4%BD%A0%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8ip:8080/web)
> 
> 
> 这就代表你部署成功了 调试API就执行了[http：//你的服务器ip：8080/v1/chat/completions](http://%E4%BD%A0%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8ip:8080/v1/chat/completions) Web界面在[http：//你的服务器ip：8080/web](http://%E4%BD%A0%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8ip:8080/web)
感谢，我还以为直接打开就是web端
