### ISSUE TITLE
unofficial api对接不正常

### ISSUE THREAD

**Issue by zengge99** [aurora-develop/aurora#199]
chatgpt-web：https://github.com/Chanzhaoyu/chatgpt-web
设置：USE_DB=true，环境：koyeb
接口：/backend-api/conversation
第一条消息正常，第二条消息开始提示错误。大佬帮忙看看呢。
ChatGPT error 404: {"error":{"code":"error","message":{"code":"conversation_not_found","message":"Conversation not found"},"param":null,"type":"404 Not Found"}}

**Comment by xiaozhou26** [comment]
#193

**Comment by zengge99** [comment]
> #193

谢谢！搞懂了，只要填有效的access token就可以隔离网页上的多个会话。

**Comment by zengge99** [comment]
设置chatgpt-web的OPENAI_ACCESS_TOKEN，如果免登陆就设置成任意uuid，如果用自己的账号就填网页access token。非常感谢!
