### ISSUE TITLE
Authorization 问题

### ISSUE THREAD

**Issue by leejay001** [aurora-develop/aurora#200]
docker run -d \
  --name aurora \
  -p 127.0.0.1:8081:8080 \
  -e BASE_URL="https://chat.openai.com/backend-api" \
  -e Authorization="xxxx" \
  ghcr.io/aurora-develop/aurora:latest

这样部署后，通过域名访问接口，发现Authorization不传递或者传递错误都能用，是我的方式有问题吗？还请指教

**Comment by xiaozhou26** [comment]
你authorization怎么设置的
