### ISSUE TITLE
访问Web端报404错误

### ISSUE THREAD

**Issue by vllv** [aurora-develop/aurora#201]
1. API可以正常返回数据
![image](https://github.com/aurora-develop/aurora/assets/1285461/ba444603-4168-4c29-8498-492355c818eb)

2. curl 访问baidu也可以
![image](https://github.com/aurora-develop/aurora/assets/1285461/9d09c592-cce1-48d8-8b87-fbfe12c522c8)

3. curl 访问 http://127.0.01:8080/web 报404
![image](https://github.com/aurora-develop/aurora/assets/1285461/5abdd7f9-9390-4ad8-aad0-562c42b1dfa3)

5. 网页端访问也是报404
![image](https://github.com/aurora-develop/aurora/assets/1285461/5af46431-0824-49b3-9c83-3614ac0a9c86)

**Comment by biandh** [comment]
试试把浏览器的代理取消

**Comment by aleung** [comment]
我部署在vercel上也是，用 curl 测试 API 是正常的，但访问 `/web` 就是 404 错误。今天刚刚部署的。

**Comment by vllv** [comment]
> 试试把浏览器的代理取消
浏览器没有代理，直接在vps本地访问web页面都不行

**Comment by xiaozhou26** [comment]
vercel没有web端
