### ISSUE TITLE
响应体返回的usge内容是0

### ISSUE THREAD

**Issue by isinry** [aurora-develop/aurora#206]
<img width="548" alt="image" src="https://github.com/aurora-develop/aurora/assets/27894034/8c78c7af-3ac1-4b7b-8ee0-b70fb225dd61">

```
{
        "prompt_tokens": 0,
        "completion_tokens": 0,
        "total_tokens": 0
    }
```
这三个皆为0，导致对接chatgpt-on-wechat的时候总是给我返回error，chatgpt-on-wechat做了判断
<img width="825" alt="image" src="https://github.com/aurora-develop/aurora/assets/27894034/9f7c6c3b-ed7a-4dad-9430-11ccaa000aac">

**Comment by xiaozhou26** [comment]
#202
