### ISSUE TITLE
建议在环境变量中增加默认OpenAI接口选项

### ISSUE THREAD

**Issue by Cide999** [aurora-develop/aurora#214]
原因：
本人用的是docker部署，用nginx代理域名之后，网站仍需填写/web/路径比较麻烦

举例：
1.用IP直接部署，http://127.0.0.1:8080是接口，http://127.0.0.1:8080/web/是用户访问的界面

2.现在用nginx代理之后，如果我直接代理 http://127.0.0.1:8080/web/ 到 gpt.xxxxxx.com 这个域名，那么我访问gpt.xxxxxx.com这个域名网页是正常的，但是接口那边是错误的，因为我并没有代理 http://127.0.0.1:8080。而且网站会报错，提示无权使用。

3.换个方式，如果我代理 http://127.0.0.1:8080 到 gpt.xxxxxx.com 这个域名，那么我访问的时候需要写成 gpt.xxxxxx.com/web/ 来访问，如果不带路径"/web/"就只返回JSON数据，这样对其他的电脑小白来说可能会有点难度。

最后我想到的解决办法：
第一步代理 http://127.0.0.1:8080 到 gptproxy.xxxxxx.com，第二步代理 http://127.0.0.1:8080/web/ 到 gpt.xxxxxx.com，访问gpt.xxxxxx.com这个网页后，这样只需要修改网页设置中的OpenAI接口为 gptproxy.xxxxxx.com 即可正常使用。

希望作者能够在docker环境变量中增加一下默认OpenAI接口选项，如需赞助，请提供链接，谢谢。

**Comment by xiaozhou26** [comment]
？

**Comment by Cide999** [comment]
> ？

作者是不是没用过nginx，😂

**Comment by xiaozhou26** [comment]
nginx直接代理有问题的

**Comment by Cide999** [comment]
> nginx直接代理有问题的

可以正常用，需要改点东西

**Comment by learnLi** [comment]
> 原因： 本人用的是docker部署，用nginx代理域名之后，网站仍需填写/web/路径比较麻烦
> 
> 举例： 1.用IP直接部署，[http://127.0.0.1:8080是接口，http://127.0.0.1:8080/web/是用户访问的界面](http://127.0.0.1:8080%E6%98%AF%E6%8E%A5%E5%8F%A3%EF%BC%8Chttp://127.0.0.1:8080/web/%E6%98%AF%E7%94%A8%E6%88%B7%E8%AE%BF%E9%97%AE%E7%9A%84%E7%95%8C%E9%9D%A2)
> 
> 2.现在用nginx代理之后，如果我直接代理 http://127.0.0.1:8080/web/ 到 gpt.xxxxxx.com 这个域名，那么我访问gpt.xxxxxx.com这个域名网页是正常的，但是接口那边是错误的，因为我并没有代理 [http://127.0.0.1:8080。而且网站会报错，提示无权使用。](http://127.0.0.1:8080%E3%80%82%E8%80%8C%E4%B8%94%E7%BD%91%E7%AB%99%E4%BC%9A%E6%8A%A5%E9%94%99%EF%BC%8C%E6%8F%90%E7%A4%BA%E6%97%A0%E6%9D%83%E4%BD%BF%E7%94%A8%E3%80%82)
> 
> 3.换个方式，如果我代理 http://127.0.0.1:8080 到 gpt.xxxxxx.com 这个域名，那么我访问的时候需要写成 gpt.xxxxxx.com/web/ 来访问，如果不带路径"/web/"就只返回JSON数据，这样对其他的电脑小白来说可能会有点难度。
> 
> 最后我想到的解决办法： 第一步代理 http://127.0.0.1:8080 到 gptproxy.xxxxxx.com，第二步代理 http://127.0.0.1:8080/web/ 到 gpt.xxxxxx.com，访问gpt.xxxxxx.com这个网页后，这样只需要修改网页设置中的OpenAI接口为 gptproxy.xxxxxx.com 即可正常使用。
> 
> 希望作者能够在docker环境变量中增加一下默认OpenAI接口选项，如需赞助，请提供链接，谢谢。

nginx proxy manager 了解一下

**Comment by Cide999** [comment]
> > 原因： 本人用的是docker部署，用nginx代理域名之后，网站仍需填写/web/路径比较麻烦
> > 举例： 1.用IP直接部署，[http://127.0.0.1:8080是接口，http://127.0.0.1:8080/web/是用户访问的界面](http://127.0.0.1:8080%E6%98%AF%E6%8E%A5%E5%8F%A3%EF%BC%8Chttp://127.0.0.1:8080/web/%E6%98%AF%E7%94%A8%E6%88%B7%E8%AE%BF%E9%97%AE%E7%9A%84%E7%95%8C%E9%9D%A2)
> > 2.现在用nginx代理之后，如果我直接代理 http://127.0.0.1:8080/web/ 到 gpt.xxxxxx.com 这个域名，那么我访问gpt.xxxxxx.com这个域名网页是正常的，但是接口那边是错误的，因为我并没有代理 [http://127.0.0.1:8080。而且网站会报错，提示无权使用。](http://127.0.0.1:8080%E3%80%82%E8%80%8C%E4%B8%94%E7%BD%91%E7%AB%99%E4%BC%9A%E6%8A%A5%E9%94%99%EF%BC%8C%E6%8F%90%E7%A4%BA%E6%97%A0%E6%9D%83%E4%BD%BF%E7%94%A8%E3%80%82)
> > 3.换个方式，如果我代理 http://127.0.0.1:8080 到 gpt.xxxxxx.com 这个域名，那么我访问的时候需要写成 gpt.xxxxxx.com/web/ 来访问，如果不带路径"/web/"就只返回JSON数据，这样对其他的电脑小白来说可能会有点难度。
> > 最后我想到的解决办法： 第一步代理 http://127.0.0.1:8080 到 gptproxy.xxxxxx.com，第二步代理 http://127.0.0.1:8080/web/ 到 gpt.xxxxxx.com，访问gpt.xxxxxx.com这个网页后，这样只需要修改网页设置中的OpenAI接口为 gptproxy.xxxxxx.com 即可正常使用。
> > 希望作者能够在docker环境变量中增加一下默认OpenAI接口选项，如需赞助，请提供链接，谢谢。
> 
> nginx proxy manager 了解一下

😂nginx proxy manager一样呀，我也试过的，难道说你有更好的做法？欢迎详细说明👍

**Comment by chris-ss** [comment]
接口用另外的前缀代理就行了呀
api.xxx.com 代理接口
chat.xxx.com 代理web

**Comment by MagicalMadoka** [comment]
楼上正解，一个域名其实也可以，自己看nginx文档进行配置
