### ISSUE TITLE
API使用超出限额，请检查您的账单！

### ISSUE THREAD

**Issue by DudeCode** [aurora-develop/aurora#223]
有人遇到这种提示吗？什么什么情况

**Comment by iberxilong** [comment]
是  Trigger API call rate limit, please try again later! 这种情况吗？

**Comment by DudeCode** [comment]
APl usage exceeded limit,please check your bil!!

**Comment by MagicalMadoka** [comment]
429了，问多了。请使用ip池或其他办法解决
