### ISSUE TITLE
最新的镜像出现401错误，前几个都能正常使用。

### ISSUE THREAD

**Issue by crosspacific** [aurora-develop/aurora#23]
最新的镜像出现401错误。这个镜像（[sha256:0b7131bc7abd455bfc531a6350be01cb64c6309647c76c7a173519014ad552c7](https://github.com/orgs/aurora-develop/packages/container/aurora/198988624)）及以前的可以正常使用。

**Comment by lingoox** [comment]
401是因为uuid可能和正常账号重复了。导致校验了access_token

**Comment by crosspacific** [comment]
那我再试试。

**Comment by zwmmm** [comment]
一直 401 换了美国节点也不行

**Comment by geekbb** [comment]
> 最新的镜像又出现 {"code":500,"message":"error sending request","param":{},"type":"InitTurnStile_request_error"}

对的，我以前都知道，今天换最新镜像又出现 {"code":500,……请问能修吗？

**Comment by chris-ss** [comment]
> 最新的镜像又出现  {"code":500,"message":"error sending request","param":{},"type":"InitTurnStile_request_error"}

same，本来正常，更新了最新镜像以后500

**Comment by chris-ss** [comment]
在[#61](https://github.com/aurora-develop/aurora/issues/61)中作者说是IP不支持，可是我更新镜像前才用的好好的，更新镜像后就报错这个了，明显不是IP不支持呀

**Comment by crosspacific** [comment]
> 在[#61](https://github.com/aurora-develop/aurora/issues/61)中作者说是IP不支持，可是我更新镜像前才用的好好的，更新镜像后就报错这个了，明显不是IP不支持呀

作者说今天修复

**Comment by crosspacific** [comment]
> > 最新的镜像又出现 {"code":500,"message":"error sending request","param":{},"type":"InitTurnStile_request_error"}
> 
> 对的，我以前都支持，今天换最新镜像又出现 {"code":500,……请问能修吗？

已经修复好了。最新的可以用了。
