### ISSUE TITLE
failed to get chat requirements

### ISSUE THREAD

**Issue by amrpyt** [aurora-develop/aurora#237]
```
{
    "code": 403,
    "message": "failed to get chat requirements",
    "param": {},
    "type": "InitTurnStile_request_error"
}
```

I'm using : https://atomic-kaja-amrpyt.koyeb.app/v1/chat/completions

**Comment by xiaozhou26** [comment]
免费容器很多人公用一个ip，很容易黑

**Comment by amrpyt** [comment]
> 免费容器很多人公用一个ip，很容易黑

So what's the solution?

**Comment by amrpyt** [comment]
> 免费容器很多人公用一个ip，很容易黑

So what's the solution?

**Comment by xiaozhou26** [comment]
> > 免费容器很多人公用一个ip，很容易黑
> 
> So what's the solution?

change ip address
