### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by meekr** [aurora-develop/aurora#239]
终端运行 curl
curl --location 'http://127.0.0.1:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "stream": true
   }'

返回：{"error":"Post \"https://chat.openai.com/cdn-cgi/challenge-platform/h/b/jsd/r/df7cec3ee9a25612\": net/http: TLS handshake timeout"}

**Comment by xiaozhou26** [comment]
出cf盾了
