### ISSUE TITLE
网关超时是什么原因，是指了 apikey 也一样。

### ISSUE THREAD

**Issue by gimlyu** [aurora-develop/aurora#243]
Master 拉代码编译运行的：服务不可用。用的 azure US 的服务器。

> $ chmod +x ./aurora
> $ ./aurora 
> 2024/05/16 09:52:35 3958 0.0.0.0:8080
> [GIN] 2024/05/16 - 09:52:57 | 200 |      69.101µs |  169.150.203.18 | GET      "/"
> [GIN] 2024/05/16 - 09:53:04 | 200 |  893.891149ms |  169.150.203.18 | GET      "/web/"
> [GIN] 2024/05/16 - 09:53:06 | 200 |  468.968003ms |  169.150.203.18 | GET      "/web/avatar.png"
> [GIN] 2024/05/16 - 09:53:06 | 200 |     181.803µs |  169.150.203.18 | GET      "/web/icon.png"
> [GIN] 2024/05/16 - 09:53:10 | 403 |  1.144891832s |  169.150.203.18 | POST     "/v1/chat/completions"
> [GIN] 2024/05/16 - 09:56:03 | 403 |  1.462002591s |   106.38.90.217 | POST     "/v1/chat/completions"
> 
```bash
curl --location 'http://USIP:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "stream": true
   }'
```
前端显示网关超时，curl 以上命令返回：
`Unusual activity has been detected from your device. Try again later`
哪里不对哦

**Comment by EvansSec** [comment]
我的也是，web页面显示“网关错误或超时，请稍后重试！”
CURL结果：
curl --location 'http://IP:8888/v1/chat/completions' \hat/completions' \
--header 'Content-Type: application/json' \
--data '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "stream": true
   }'
{"code":403,"message":"failed to get chat requirements","param":{},"type":"InitTurnStile_request_error"}

**Comment by li-linfeng** [comment]
+1 更新了最新镜像也不行

**Comment by xiaozhou26** [comment]
项目闭源了，仅支持部分官方未拉黑ip，编译部署已删
