### ISSUE TITLE
关于群晖nas用docker部署的网络问题

### ISSUE THREAD

**Issue by doublerighthu** [aurora-develop/aurora#245]
作者你好,我用群晖nas中的docker做了部署.因为需要给群晖nas代理网络才能正常使用.而我的clash是部署在路由器上的.同时其他服务不需要代理网络.
所以想问下,在路由器端,是不是只要给aurora的网络端口列入clash 白名单即可?
我将默认的8080端口路由器端做了端口转发,同时也加入了clash白名单,但是好像还是不行呢.

如果我将整个nas都列入clash都白名单,项目是可以正常使用的.

**Comment by xiaozhou26** [comment]
把原端口和端口转发都白名单
