### ISSUE TITLE
调用返回

### ISSUE THREAD

**Issue by worf2000** [aurora-develop/aurora#255]
{
    "code": 403,
    "message": "failed to get chat requirements",
    "param": {},
    "type": "InitTurnStile_request_error"
}

**Comment by xiaozhou26** [comment]
一直是这个报错？

**Comment by Komorebi-yaodong** [comment]
我也遇到了
![image](https://github.com/user-attachments/assets/864f1a42-5745-45f8-92fa-6e11ef3b858e)

**Comment by xiaozhou26** [comment]
ip问题

**Comment by xiaozhou26** [comment]
已修复
