### ISSUE TITLE
runtime error: panic

### ISSUE THREAD

**Issue by ffreemt** [aurora-develop/aurora#256]
![image](https://github.com/user-attachments/assets/18a0d81f-2d2d-4512-a221-d81c732d8f41)

感谢佬提供这么好的软件。

ubunut里用库里的 docker-compose.yml，中间有几次请求成功了，可以看到"This is a test"的输出。然后就请求时啥反应都没有。docker那边出现上面的信息。再发请求还是一样啥反应都没有，docker那边还是出现上面的信息。重启docker-compose down/up 还是一样的情况。

会是啥原因呢，有没啥办法恢复。感谢。

**Comment by xiaozhou26** [comment]
指针问题，有没有更详细的步骤，可以让我复现

**Comment by xiaozhou26** [comment]
已修复

**Comment by ffreemt** [comment]
太好了，感谢
