### ISSUE TITLE
无法打开了 为什么

### ISSUE THREAD

**Issue by MissAlang** [aurora-develop/aurora#257]
无法打开了 为什么
ai.waimao88.com/:1 Access to script at 'https://cdn.staticfile.org/KaTeX/0.16.9/katex.min.js' from origin 'https://ai.waimao88.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is pr

**Comment by xiaozhou26** [comment]
静态网页的js的cdn寄了，

**Comment by xiaozhou26** [comment]
已修复

**Comment by MissAlang** [comment]
这边如何更新

**Comment by xiaozhou26** [comment]
> 这边如何更新

更新docker镜像就行了
