### ISSUE TITLE
支持用户登录

### ISSUE THREAD

**Issue by ghost** [aurora-develop/aurora#3]

**Comment by tisfeng** [comment]
希望能支持用户登录。

不确定是不是和用户登录关，我发现未登录状态下，ChatGPT 似乎比较笨。

下面是我分别在登录状态下和无痕浏览器未登录状态的测试：

## 登录状态
<img width="1117" alt="image" src="https://github.com/aurora-develop/aurora/assets/25194972/12af46b1-e7fa-4716-a171-d20364f2465c">

## 未登录状态
<img width="1126" alt="image" src="https://github.com/aurora-develop/aurora/assets/25194972/ac3ca4c6-affe-442b-a1fd-838ca8cfc540">

## 测试题目
```
你是一个高智商的问答小助手，请回答下面这些问题：

1. 鲁迅和周树人的关系怎么样？

2. 新中国成立那一年，美国总统是谁？

3. 天为什么是蓝的？

4. 陨石为什么总能落在陨石坑里？

5. 80级地震会发生什么，破坏力如何？

6. 在厨房的桌子上有一个杯子，杯子中有一个玻璃球，我把杯子拿到卧室的桌子上，然后把杯子的杯口朝下放在桌子上，随后我把杯子拿起回到厨房。请问，现在玻璃球在哪里？

7. 鸡兔同笼，共35只头，94只脚，问鸡兔各多少？

8. 解方程：x^2+4=20

9. Kylar 去商店为新公寓购买玻璃杯，一个玻璃杯 5 美元，但第二个玻璃杯售价仅为原价的 60%。Kylar 想买 16 个玻璃杯，他需要付多少钱？

10. 1个苹果=2个梨，3个梨=4个橙子，6个橙子=7个香蕉，请问56个香蕉等于多少个苹果？
```

**Comment by tisfeng** [comment]
有点奇怪，我登录了另一个空白账号，结果似乎也差不多。。。不知道是大模型的不确定性，还是和账号历史数据有关 🫠
