### ISSUE TITLE
"error":{"code":"json: cannot unmarshal array into Go struct field api_message.messages.content

### ISSUE THREAD

**Issue by dqzboy** [aurora-develop/aurora#50]
ChatGPT error 400: {"error":{"code":"json: cannot unmarshal array into Go struct field api_message.messages.content of type string","message":"Request must be proper JSON","param":null,"type":"invalid_request_error"}}
<img width="1201" alt="image" src="https://github.com/aurora-develop/aurora/assets/42825450/41903167-b8e8-4a63-a7e9-40e099bb1c58">

大佬这个咋处理

**Comment by dqzboy** [comment]
> ChatGPT error 400: {"error":{"code":"json: cannot unmarshal array into Go struct field api_message.messages.content of type string","message":"Request must be proper JSON","param":null,"type":"invalid_request_error"}} <img alt="image" width="1201" src="https://private-user-images.githubusercontent.com/42825450/319450208-41903167-b8e8-4a63-a7e9-40e099bb1c58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDc5NDIsIm5iZiI6MTcxMjIwNzY0MiwicGF0aCI6Ii80MjgyNTQ1MC8zMTk0NTAyMDgtNDE5MDMxNjctYjhlOC00YTYzLWE3ZTktNDBlMDk5YmIxYzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA1MTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkY2ZlMWUxYTk5MDlmYzBhNzgxZTYyMGMyYTk5YTJlYzM2NTM5OTIxZTliNTRmNTQwMjNkMzgyNjM0MTFmMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KE36ELuGoiGZVdGQd2Ym0QGqrP0onKl1vhY3Awhn9Sg">
> 
> 大佬这个咋处理

发现问题了  不支持携带上下文，关闭上下文就正常了

**Comment by lingoox** [comment]
你的messages格式错误了，把请求的json贴一下

**Comment by lingoox** [comment]
{ role: 'user', content: [ { type: 'text', text: 'hello' } ] },你这个不是错误了吗？ 字符串你传了数组

**Comment by dqzboy** [comment]
> { role: 'user', content: [ { type: 'text', text: 'hello' } ] },你这个不是错误了吗？ 字符串你传了数组

这个是那个客户端默认就是这样的，不是我去传的；
