### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zengge99** [aurora-develop/aurora#61]
root@vm3:~/chatgpt-qq# curl --location 'http://127.0.0.1:8080/v1/chat/completions' --header 'Content-Type: application/json' --data '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "stream": true
   }'
{"code":500,"message":"error sending request","param":{},"type":"InitTurnStile_request_error"}

**Comment by xiaozhou26** [comment]
ip不支持

**Comment by xiaozhou26** [comment]
> 可以支持挂代理吗？

可以环境变量中

PROXY_URL=your_proxy_url

**Comment by zengge99** [comment]
谢谢

**Comment by dqzboy** [comment]
> > 可以支持挂代理吗？
> 
> 可以环境变量中
> 
> PROXY_URL=your_proxy_url

在docker compos配置了代理参数，没有生效
![IMG_2066](https://github.com/aurora-develop/aurora/assets/42825450/3a587163-3cb4-48ab-b69b-192821165f03)
