### ISSUE TITLE
非常棒的应用

### ISSUE THREAD

**Issue by shawokou123** [aurora-develop/aurora#62]
之前我一直使用： [ChatGPT-to-API](https://github.com/xqdoo00o/ChatGPT-to-API)

后来这个不能用，目前这个aurora是我用过最好的同类应用，可以直接用api ！！！希望再接再厉！

**Comment by alexallen1** [comment]
Render部署  的确非常棒。省时省力又省钱

**Comment by MagicalMadoka** [comment]
感谢支持
