### ISSUE TITLE
Can you support python？

### ISSUE THREAD

**Issue by long202258** [aurora-develop/aurora#71]
Can you support python？ thank you

**Comment by xiaozhou26** [comment]
What do you mean?

**Comment by long202258** [comment]
> 你是什么意思？

Can I make this project support python?

**Comment by long202258** [comment]
> 你是什么意思？

Can you make this project support python?

**Comment by xiaozhou26** [comment]
import requests
import json

url = 'http://127.0.0.1:8080/v1/chat/completions'
headers = {'Content-Type': 'application/json'}
data = {
"model": "gpt-3.5-turbo",
"messages": [{"role": "user", "content": "Say this is a test!"}],
"stream": True
}

response = requests.post(url, headers=headers, data=json.dumps(data))

print('HTTP Status Code:', response.status_code)
print('Response Body:', response.text)

if response.status_code == 200:
try:
print('JSON Response:', response.json())
except json.JSONDecodeError:
print('Could not decode the response as JSON')
else:
print('Received an error:', response.status_code)

**Comment by long202258** [comment]
> 导入请求导入 JSON
> 
> url = ['http://127.0.0.1:8080/v1/chat/completions](http://127.0.0.1:8080/v1/chat/completions)' headers = {'Content-Type'： 'application/json'} data = { “model”： “gpt-3.5-turbo”， “messages”： [{“role”： “user”， “content”： “Say this is a test！”}]， “stream”： True }
> 
> 响应 = requests.post（url， headers=headers， data=json.dumps（data））
> 
> print（'HTTP 状态代码：'， response.status_code） print（'响应正文：'， response.text）
> 
> if response.status_code == 200： try： print（'JSON Response：'， response.json（）） 除了 json。JSONDecodeError： print（'无法将响应解码为 JSON'） else： print（'收到错误：'， response.status_code）

![image](https://github.com/aurora-develop/aurora/assets/97136192/51331573-30d2-40d6-bab2-fa7997d4920c)
一直报这个错误

**Comment by xiaozhou26** [comment]
这不是能用嘛

**Comment by learnLi** [comment]
> > 导入请求导入 JSON
> > url = ['http://127.0.0.1:8080/v1/chat/completions](http://127.0.0.1:8080/v1/chat/completions)' headers = {'Content-Type'： 'application/json'} data = { “model”： “gpt-3.5-turbo”， “messages”： [{“role”： “user”， “content”： “Say this is a test！”}]， “stream”： True }
> > 响应 = requests.post（url， headers=headers， data=json.dumps（data））
> > print（'HTTP 状态代码：'， response.status_code） print（'响应正文：'， response.text）
> > if response.status_code == 200： try： print（'JSON Response：'， response.json（）） 除了 json。JSONDecodeError： print（'无法将响应解码为 JSON'） else： print（'收到错误：'， response.status_code）
> 
> ![image](https://private-user-images.githubusercontent.com/97136192/319629401-51331573-30d2-40d6-bab2-fa7997d4920c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNDgzNjYsIm5iZiI6MTcxMjI0ODA2NiwicGF0aCI6Ii85NzEzNjE5Mi8zMTk2Mjk0MDEtNTEzMzE1NzMtMzBkMi00MGQ2LWJhYjItZmE3OTk3ZDQ5MjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE2Mjc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNGJkZWQxZmVhYTA5MzRlN2M4ODZkN2E2MDJlODI4MmZmMTk5MGFmYjBiY2VmYWM2OTc1ODQwN2I0ZDI4M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lccmyUyMu_fIKkIDDzxUv__wDphDla3iVa-uOM-xg9I) 一直报这个错误

用openai的官方包就行了

**Comment by long202258** [comment]
> 用openai的官方包就行了

大哥，能给个示例代码吗

**Comment by long202258** [comment]
> 这不是能用嘛

怎么转换成文本呀，不懂呢
