### ISSUE TITLE
为什么提示500错误

### ISSUE THREAD

**Issue by lammy2021** [aurora-develop/aurora#89]
如题，昨天晚上还是可以的，今天就总是500了，拼命重试可以刷新出几次可以正常回答。

**Comment by xiaozhou26** [comment]
更新镜像就好了

**Comment by lammy2021** [comment]
> 更新镜像就好了

好的，谢谢大佬，刚刚看到你的库在pending就觉得可能是是了。已star，希望可以长久维护❤️❤️
