### ISSUE TITLE
401错误是不是机器的ip不支持运行

### ISSUE THREAD

**Issue by lammy2021** [aurora-develop/aurora#91]
{
  "code": 401,
  "message": "response status code is not 200",
  "param": {},
  "type": "InitTurnStile_request_error"
}

有另外一台ip可以正常运行，这台KR的就不行，但是在KR的chatgptnext上面填我另外一条的api就可以

**Comment by xiaozhou26** [comment]
重新拉镜像。多试几次

**Comment by lammy2021** [comment]
> 重新拉镜像。多试几次

ok

**Comment by xiaozhou26** [comment]
重新刷应该就好了

**Comment by xiaozhou26** [comment]
#104
