### ISSUE TITLE
韩国春川一直401  部署了几遍  是ip问题？

### ISSUE THREAD

**Issue by cshitian** [aurora-develop/aurora#97]
韩国春川一直401  部署了几遍  是ip问题？

{"code":401,"message":"response status code is not 200","param":{},"type":"InitTurnStile_request_error"}

**Comment by xiaozhou26** [comment]
应该是，节点能免登吗

**Comment by cshitian** [comment]
> 应该是，节点能免登吗



> 应该是，节点能免登吗

不知道 我这个是甲骨文申请的免费服务器

**Comment by callacat** [comment]
> > 应该是，节点能免登吗
> 
> > 应该是，节点能免登吗
> 
> 不知道 我这个是甲骨文申请的免费服务器

你搭建个节点试一下，我试另一个项目是不支持的，你估计也是

**Comment by cshitian** [comment]
> > > 应该是，节点能免登吗
> > 
> > 
> > > 应该是，节点能免登吗
> > 
> > 
> > 不知道 我这个是甲骨文申请的免费服务器
> 
> 你搭建个节点试一下，我试另一个项目是不支持的，你估计也是

试过了 也不行。 估计就是ip问题

**Comment by tuzh6** [comment]
是IP问题，已确定。

**Comment by xiaozhou26** [comment]
baseurl换我们的网关可以使用

**Comment by xiaozhou26** [comment]
#104
